#!/bin/bash

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "Usage: download-model <release-version> <shasum>"
    echo "The shasum is calculated by 'find <model-dir>/. -type f -exec sha256sum {} + | sort | sha256sum'"
    exit 1
fi

VERSION="$1"
EXPECTED_HASH="$2"
MODEL_PARENT_DIR="/home/pi"
MODEL_DIR="${MODEL_PARENT_DIR}/tflite"
TAR_FILENAME="inc3-tflite-15122023.tar"
URL="https://github.com/TheCacophonyProject/AI-Model/releases/download/${VERSION}/${TAR_FILENAME}"

# This will check that the files are correct by:
# - Find all files for the model.
# - Sort them so the hashes are in a consistent order.
# - Hash the combined hashes to make sure that the files are as expected.
check_files_hash() {
    local generated_hash=$(find "${MODEL_DIR}/." -type f -exec sha256sum {} + | sort | sha256sum | awk '{print $1}')
    if [ "$generated_hash" = "$EXPECTED_HASH" ]; then
        echo "Files hash matches."
        return 0
    else
        echo "Files hash mismatch!"
        echo "Expected: $EXPECTED_HASH"
        echo "Found:    $generated_hash"
        return 1
    fi
}

echo "Checking if the model is already setup..."
if check_files_hash; then
    echo "Model already setup for $VERSION"
    exit 0
fi
echo "Hash mismatch. The folder may be setup for the wrong model or didn't extract correctly."

echo "Downloading $TAR_FILENAME from GitHub..."
wget -nv "$URL" --output-document="/tmp/$TAR_FILENAME"

echo "Extracting $TAR_FILENAME"
tar -xf "/tmp/$TAR_FILENAME" -C "${MODEL_PARENT_DIR}"

if check_files_hash; then
    echo "Model now setup for $VERSION"
    exit 0
else
    echo "Hash mismatch!"
    echo "Hash mismatch after downloading and extracting the model."
    exit 1
fi
