#!/bin/bash

# Get the Raspberry Pi model and filter out null bytes
MODEL=$(cat /proc/device-tree/model | tr -d '\0')

if [[ "$MODEL" == *"Raspberry Pi Zero"* ]]; then
    # If it is a Raspberry Pi Zero
    echo 1 | sudo tee /sys/class/leds/ACT/brightness > /dev/null
elif [[ "$MODEL" == *"Raspberry Pi 3"* ]]; then
    # If it is a Raspberry Pi 3
    echo 0 | sudo tee /sys/class/leds/ACT/brightness > /dev/null
    echo 0 | sudo tee /sys/devices/platform/soc/3f980000.usb/buspower > /dev/null
else
    echo "Unsupported Raspberry Pi model."
fi
