[Journal]
Storage=persistent
SystemMaxUse=1G
#  SystemMaxFileSize=2M will prevent log files that only have a few actual lines of logs being 8MB each. This would happen when the camera lost power, so journalctl would make a new log file rather than appending to the previous one.
SystemMaxFileSize=2M
SystemKeepFree=500M
MaxRetentionSec=6month
SystemMaxFiles=300
