#!/bin/bash
delaytime=$(($RANDOM % 7200))

#check for parameter 'now' for immediate run, otherwise delay
if [[ "$1" == "now" ]] ; then
  echo "Immediate upgrade requested"
else
  logger apt-updater: Waiting ${delaytime} secs before updating
  sleep ${delaytime}
fi


logger apt-updater: Waking up the modem
systemctl restart stay-on

((count = 60))                           # Try 60 pings
while [[ $count -ne 0 ]] ; do
    ping -c 1 8.8.8.8                    # Try once.
    rc=$?
    if [[ $rc -eq 0 ]] ; then
        ((count = 1))                    # If okay, flag loop exit.
    else
        sleep 10                         # If not delay 10 secs and retry
    fi
    ((count = count - 1))                # So we don't go forever.
done

if [[ $rc -eq 0 ]] ; then                # Did ping succeed in end
    logger apt-updater: Updating now
    apt-get update -o Dir::Etc::SourceList=/etc/apt/apt-updater-sources.list -o Dir::Etc::SourceParts=/etc/apt/apt-updater-sources.list.d
    logger apt-updater: Upgrading now
    apt-get upgrade -y -o Dir::Etc::SourceList=/etc/apt/apt-updater-sources.list -o Dir::Etc::SourceParts=/etc/apt/apt-updater-sources.list.d
    rc=$?
    if [[ $rc -eq 0 ]] ; then
      logger apt-updater: Upgrade SUCCESS
    else
      logger apt-updater: ERROR: Upgrade FAILED
      dbus-send --system --type=method_call --print-reply\
         --dest=org.cacophony.Events /org/cacophony/Events/
         org.cacophony.Events.Add\
         string:'{"apt-updater":"apt-get update failed"}'\
         string:systemError\
         int64:`date +%s`000000000
    fi


    logger apt-updater: Update complete
else
    logger apt-updater: Failed to get internet connection
fi
systemctl stop stay-on
