# Checkout all three branches, aggregate version info, and commit changes
# to each branch if any of the version information in any branch has changed.

name: aggregate-version-info
env:
  GITHUB_TOKEN: ${{ secrets.CACOPHONY_BOT_TOKEN }}
on: [push, workflow_dispatch]
jobs:
  aggregate-version-info:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: dev
          ref: dev
      - uses: actions/checkout@v4
        with:
          path: prod
          ref: prod
      - uses: actions/checkout@v4
        with:
          path: test
          ref: test
      - uses: actions/checkout@v4
        with:
          repository: TheCacophonyProject/salt-version-info
          path: salt-version-info
          token: ${{ secrets.CACOPHONY_BOT_TOKEN }}
          persist-credentials: true
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 20.x
      - shell: bash
        run: |
          cd dev/.github/workflows
          npm i
          npm run aggregate-versions ${{ github.repository }}
